## 0. Import

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

## 1. Load data

In [2]:
df = pd.read_csv('cleaned_data.csv')

In [3]:
df

,Unnamed: 0,CustomerID,ReportedFraud,DateOfIncident,TypeOfIncident,SeverityOfIncident,AuthoritiesContacted,IncidentState,IncidentCity,IncidentAddress,...,DateOfPolicyCoverage,InsurancePolicyState,Policy_CombinedSingleLimit,Policy_Deductible,PolicyAnnualPremium,InsuredRelationship,VehicleID,VehicleMake,VehicleModel,VehicleYOM
0,0,Cust20065,N,2015-01-09,Multi-vehicle Collision,Total Loss,Other,State9,City4,Location 1404,...,1998-11-14,State2,250/500,2000,1142.87,own-child,Vehicle30662,Mercedes,E400,2005
1,1,Cust37589,N,2015-02-20,Single Vehicle Collision,Minor Damage,Ambulance,State4,City3,Location 1675,...,2000-08-19,State2,100/300,1000,1274.38,own-child,Vehicle17183,Toyota,Highlander,2010
2,2,Cust24312,N,2015-01-14,Multi-vehicle Collision,Major Damage,Ambulance,State5,City2,Location 1546,...,2000-06-23,State1,500/1000,745,1269.93,other-relative,Vehicle33982,Volkswagen,Passat,2002
3,3,Cust5493,Y,2015-01-07,Multi-vehicle Collision,Major Damage,Ambulance,State7,City4,Location 1413,...,1992-01-15,State2,100/300,986,1218.60,other-relative,Vehicle12299,Toyota,Highlander,2011
4,4,Cust7704,Y,2015-02-26,Multi-vehicle Collision,Major Damage,Other,State4,City6,Location 1367,...,2001-09-23,State3,250/500,576,1431.02,unmarried,Vehicle30447,Ford,Wrangler,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27144,28831,Cust9773,N,2015-02-13,Single Vehicle Collision,Minor Damage,Fire,State7,City3,Location 1324,...,2007-02-07,State2,250/500,1000,1108.55,unmarried,Vehicle24503,Nissan,RSX,2002
27145,28832,Cust38439,N,2015-01-19,Multi-vehicle Collision,Total Loss,Police,State5,City3,Location 1880,...,2006-10-18,State2,100/300,1008,1551.84,own-child,Vehicle9733,Accura,RSX,2014
27146,28833,Cust38444,N,2015-01-21,Multi-vehicle Collision,Total Loss,Police,State5,City7,Location 1632,...,2011-11-23,State1,100/300,660,1119.32,not-in-family,Vehicle1823,Saab,RSX,2013
27147,28834,Cust26466,N,2015-01-02,Parked Car,Trivial Damage,None,State4,City7,Location 1364,...,1997-08-04,State3,250/1000,1674,1229.88,wife,Vehicle9113,Accura,RSX,2004
27148,28835,Cust29555,N,2015-01-16,Single Vehicle Collision,Total Loss,Police,State8,City7,Location 1950,...,2008-01-04,State2,250/1000,500,1341.72,wife,Vehicle7530,Volkswagen,RSX,2009

In [4]:
df.drop('Unnamed: 0', axis = 1, inplace = True)
df

,CustomerID,ReportedFraud,DateOfIncident,TypeOfIncident,SeverityOfIncident,AuthoritiesContacted,IncidentState,IncidentCity,IncidentAddress,IncidentTime,...,DateOfPolicyCoverage,InsurancePolicyState,Policy_CombinedSingleLimit,Policy_Deductible,PolicyAnnualPremium,InsuredRelationship,VehicleID,VehicleMake,VehicleModel,VehicleYOM
0,Cust20065,N,2015-01-09,Multi-vehicle Collision,Total Loss,Other,State9,City4,Location 1404,19,...,1998-11-14,State2,250/500,2000,1142.87,own-child,Vehicle30662,Mercedes,E400,2005
1,Cust37589,N,2015-02-20,Single Vehicle Collision,Minor Damage,Ambulance,State4,City3,Location 1675,14,...,2000-08-19,State2,100/300,1000,1274.38,own-child,Vehicle17183,Toyota,Highlander,2010
2,Cust24312,N,2015-01-14,Multi-vehicle Collision,Major Damage,Ambulance,State5,City2,Location 1546,21,...,2000-06-23,State1,500/1000,745,1269.93,other-relative,Vehicle33982,Volkswagen,Passat,2002
3,Cust5493,Y,2015-01-07,Multi-vehicle Collision,Major Damage,Ambulance,State7,City4,Location 1413,12,...,1992-01-15,State2,100/300,986,1218.60,other-relative,Vehicle12299,Toyota,Highlander,2011
4,Cust7704,Y,2015-02-26,Multi-vehicle Collision,Major Damage,Other,State4,City6,Location 1367,3,...,2001-09-23,State3,250/500,576,1431.02,unmarried,Vehicle30447,Ford,Wrangler,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27144,Cust9773,N,2015-02-13,Single Vehicle Collision,Minor Damage,Fire,State7,City3,Location 1324,16,...,2007-02-07,State2,250/500,1000,1108.55,unmarried,Vehicle24503,Nissan,RSX,2002
27145,Cust38439,N,2015-01-19,Multi-vehicle Collision,Total Loss,Police,State5,City3,Location 1880,19,...,2006-10-18,State2,100/300,1008,1551.84,own-child,Vehicle9733,Accura,RSX,2014
27146,Cust38444,N,2015-01-21,Multi-vehicle Collision,Total Loss,Police,State5,City7,Location 1632,16,...,2011-11-23,State1,100/300,660,1119.32,not-in-family,Vehicle1823,Saab,RSX,2013
27147,Cust26466,N,2015-01-02,Parked Car,Trivial Damage,None,State4,City7,Location 1364,12,...,1997-08-04,State3,250/1000,1674,1229.88,wife,Vehicle9113,Accura,RSX,2004
27148,Cust29555,N,2015-01-16,Single Vehicle Collision,Total Loss,Police,State8,City7,Location 1950,11,...,2008-01-04,State2,250/1000,500,1341.72,wife,Vehicle7530,Volkswagen,RSX,2009

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27149 entries, 0 to 27148
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   CustomerID                  27149 non-null  object
 1   ReportedFraud               27149 non-null  object
 2   DateOfIncident              27149 non-null  object
 3   TypeOfIncident              27149 non-null  object
 4   SeverityOfIncident          27149 non-null  object
 5   AuthoritiesContacted        27149 non-null  object
 6   IncidentState               27149 non-null  object
 7   IncidentCity                27149 non-null  object
 8   IncidentAddress             27149 non-null  object
 9   IncidentTime                27149 non-null  int64
 10  NumberOfVehicles            27149 non-null  int64
 11  BodilyInjuries              27149 non-null  int64
 12  Witnesses                   27149 non-null  int64
 13  AmountOfInjuryClaim         27149 non-null  float64
 14  AmountOfPropertyClaim       27149 non-null  float64
 15  AmountOfVehicleDamage       27149 non-null  float64
 16  InsuredAge                  27149 non-null  int64
 17  InsuredZipCode              27149 non-null  int64
 18  InsuredGender               27149 non-null  object
 19  InsuredEducationLevel       27149 non-null  object
 20  InsuredOccupation           27149 non-null  object
 21  InsuredHobbies              27149 non-null  object
 22  CapitalGains                27149 non-null  int64
 23  CapitalLoss                 27149 non-null  int64
 24  InsurancePolicyNumber       27149 non-null  int64
 25  CustomerLoyaltyPeriod       27149 non-null  int64
 26  DateOfPolicyCoverage        27149 non-null  object
 27  InsurancePolicyState        27149 non-null  object
 28  Policy_CombinedSingleLimit  27149 non-null  object
 29  Policy_Deductible           27149 non-null  int64
 30  PolicyAnnualPremium         27149 non-null  float64
 31  InsuredRelationship         27149 non-null  object
 32  VehicleID                   27149 non-null  object
 33  VehicleMake                 27149 non-null  object
 34  VehicleModel                27149 non-null  object
 35  VehicleYOM                  27149 non-null  int64
dtypes: float64(4), int64(12), object(20)
memory usage: 7.5+ MB

## 2. Categorical variable processing

## 2.1 Investigate categorical variables and drop the ones with many values

In [6]:
df.select_dtypes(include = 'O')

,CustomerID,ReportedFraud,DateOfIncident,TypeOfIncident,SeverityOfIncident,AuthoritiesContacted,IncidentState,IncidentCity,IncidentAddress,InsuredGender,InsuredEducationLevel,InsuredOccupation,InsuredHobbies,DateOfPolicyCoverage,InsurancePolicyState,Policy_CombinedSingleLimit,InsuredRelationship,VehicleID,VehicleMake,VehicleModel
0,Cust20065,N,2015-01-09,Multi-vehicle Collision,Total Loss,Other,State9,City4,Location 1404,MALE,JD,sales,video-games,1998-11-14,State2,250/500,own-child,Vehicle30662,Mercedes,E400
1,Cust37589,N,2015-02-20,Single Vehicle Collision,Minor Damage,Ambulance,State4,City3,Location 1675,FEMALE,High School,transport-moving,polo,2000-08-19,State2,100/300,own-child,Vehicle17183,Toyota,Highlander
2,Cust24312,N,2015-01-14,Multi-vehicle Collision,Major Damage,Ambulance,State5,City2,Location 1546,FEMALE,PhD,machine-op-inspct,exercise,2000-06-23,State1,500/1000,other-relative,Vehicle33982,Volkswagen,Passat
3,Cust5493,Y,2015-01-07,Multi-vehicle Collision,Major Damage,Ambulance,State7,City4,Location 1413,FEMALE,College,exec-managerial,exercise,1992-01-15,State2,100/300,other-relative,Vehicle12299,Toyota,Highlander
4,Cust7704,Y,2015-02-26,Multi-vehicle Collision,Major Damage,Other,State4,City6,Location 1367,MALE,Masters,sales,chess,2001-09-23,State3,250/500,unmarried,Vehicle30447,Ford,Wrangler
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27144,Cust9773,N,2015-02-13,Single Vehicle Collision,Minor Damage,Fire,State7,City3,Location 1324,MALE,JD,farming-fishing,basketball,2007-02-07,State2,250/500,unmarried,Vehicle24503,Nissan,RSX
27145,Cust38439,N,2015-01-19,Multi-vehicle Collision,Total Loss,Police,State5,City3,Location 1880,MALE,Associate,prof-specialty,golf,2006-10-18,State2,100/300,own-child,Vehicle9733,Accura,RSX
27146,Cust38444,N,2015-01-21,Multi-vehicle Collision,Total Loss,Police,State5,City7,Location 1632,MALE,Associate,prof-specialty,golf,2011-11-23,State1,100/300,not-in-family,Vehicle1823,Saab,RSX
27147,Cust26466,N,2015-01-02,Parked Car,Trivial Damage,None,State4,City7,Location 1364,FEMALE,Masters,exec-managerial,reading,1997-08-04,State3,250/1000,wife,Vehicle9113,Accura,RSX
27148,Cust29555,N,2015-01-16,Single Vehicle Collision,Total Loss,Police,State8,City7,Location 1950,FEMALE,PhD,tech-support,reading,2008-01-04,State2,250/1000,wife,Vehicle7530,Volkswagen,RSX

In [7]:
df.select_dtypes(include = 'O').nunique()

CustomerID                    27149
ReportedFraud                     2
DateOfIncident                   71
TypeOfIncident                    4
SeverityOfIncident                4
AuthoritiesContacted              5
IncidentState                     7
IncidentCity                      7
IncidentAddress                1000
InsuredGender                     2
InsuredEducationLevel             7
InsuredOccupation                14
InsuredHobbies                   20
DateOfPolicyCoverage           6627
InsurancePolicyState              3
Policy_CombinedSingleLimit        9
InsuredRelationship               6
VehicleID                     27149
VehicleMake                      14
VehicleModel                     39
dtype: int64

In [8]:
df.DateOfPolicyCoverage

0        1998-11-14
1        2000-08-19
2        2000-06-23
3        1992-01-15
4        2001-09-23
            ...
27144    2007-02-07
27145    2006-10-18
27146    2011-11-23
27147    1997-08-04
27148    2008-01-04
Name: DateOfPolicyCoverage, Length: 27149, dtype: object

In [9]:
Incident_date = df.DateOfIncident.sort_values().unique()
Incident_date

array(['2015-01-01', '2015-01-02', '2015-01-03', '2015-01-04',
       '2015-01-05', '2015-01-06', '2015-01-07', '2015-01-08',
       '2015-01-09', '2015-01-10', '2015-01-11', '2015-01-12',
       '2015-01-13', '2015-01-14', '2015-01-15', '2015-01-16',
       '2015-01-17', '2015-01-18', '2015-01-19', '2015-01-20',
       '2015-01-21', '2015-01-22', '2015-01-23', '2015-01-24',
       '2015-01-25', '2015-01-26', '2015-01-27', '2015-01-28',
       '2015-01-29', '2015-01-30', '2015-01-31', '2015-02-01',
       '2015-02-02', '2015-02-03', '2015-02-04', '2015-02-05',
       '2015-02-06', '2015-02-07', '2015-02-08', '2015-02-09',
       '2015-02-10', '2015-02-11', '2015-02-12', '2015-02-13',
       '2015-02-14', '2015-02-15', '2015-02-16', '2015-02-17',
       '2015-02-18', '2015-02-19', '2015-02-20', '2015-02-21',
       '2015-02-22', '2015-02-23', '2015-02-24', '2015-02-25',
       '2015-02-26', '2015-02-27', '2015-02-28', '2015-03-01',
       '2015-03-02', '2015-03-03', '2015-03-04', '2015-03-05',
       '2015-03-06', '2015-03-07', '2015-03-08', '2015-03-09',
       '2015-03-10', '2015-03-11', '2015-03-14'], dtype=object)

In [10]:
df.drop(columns = ['CustomerID','DateOfIncident', 
                   'DateOfPolicyCoverage', 'VehicleID', 'IncidentAddress'], inplace = True)

In [11]:
df.select_dtypes(include = 'O').nunique()

ReportedFraud                  2
TypeOfIncident                 4
SeverityOfIncident             4
AuthoritiesContacted           5
IncidentState                  7
IncidentCity                   7
InsuredGender                  2
InsuredEducationLevel          7
InsuredOccupation             14
InsuredHobbies                20
InsurancePolicyState           3
Policy_CombinedSingleLimit     9
InsuredRelationship            6
VehicleMake                   14
VehicleModel                  39
dtype: int64

## 2.1 Binary Categorical variable processing

In [12]:
df.ReportedFraud.value_counts()

N    19971
Y     7178
Name: ReportedFraud, dtype: int64

In [13]:
df.ReportedFraud.replace(['N', 'Y'], [0, 1], inplace = True)

In [14]:
df.ReportedFraud.value_counts()

0    19971
1     7178
Name: ReportedFraud, dtype: int64

In [15]:
df.InsuredGender.value_counts()

FEMALE    14903
MALE      12246
Name: InsuredGender, dtype: int64

In [16]:
df.InsuredGender.replace(['FEMALE', 'MALE'], [0, 1], inplace = True)

In [17]:
df.InsuredGender.value_counts()

0    14903
1    12246
Name: InsuredGender, dtype: int64

In [18]:
df.select_dtypes(include = 'O').nunique()

TypeOfIncident                 4
SeverityOfIncident             4
AuthoritiesContacted           5
IncidentState                  7
IncidentCity                   7
InsuredEducationLevel          7
InsuredOccupation             14
InsuredHobbies                20
InsurancePolicyState           3
Policy_CombinedSingleLimit     9
InsuredRelationship            6
VehicleMake                   14
VehicleModel                  39
dtype: int64

## 2.1 Categorical processing with order encoder

In [19]:
df.SeverityOfIncident.unique()

array(['Total Loss', 'Minor Damage', 'Major Damage', 'Trivial Damage'],
      dtype=object)

In [20]:
df.SeverityOfIncident.value_counts()

Minor Damage      9878
Total Loss        7724
Major Damage      7068
Trivial Damage    2479
Name: SeverityOfIncident, dtype: int64

In [21]:
df.SeverityOfIncident.replace(['Trivial Damage', 'Minor Damage', 'Major Damage', 'Total Loss'], 
                               range(4), inplace = True)

In [22]:
df.SeverityOfIncident.value_counts()

1    9878
3    7724
2    7068
0    2479
Name: SeverityOfIncident, dtype: int64

In [23]:
df.InsuredEducationLevel.value_counts()

JD             4523
High School    4285
Associate      3948
MD             3931
Masters        3901
PhD            3357
College        3204
Name: InsuredEducationLevel, dtype: int64

In [24]:
df.InsuredEducationLevel.replace(['High School', 'Associate', 'College', 'Masters', 'JD', 'MD', 'PhD'], 
                               range(7), inplace = True)

In [25]:
df.InsuredEducationLevel.value_counts()

4    4523
0    4285
1    3948
5    3931
3    3901
6    3357
2    3204
Name: InsuredEducationLevel, dtype: int64

In [26]:
df.select_dtypes(include = 'O').nunique()

TypeOfIncident                 4
AuthoritiesContacted           5
IncidentState                  7
IncidentCity                   7
InsuredOccupation             14
InsuredHobbies                20
InsurancePolicyState           3
Policy_CombinedSingleLimit     9
InsuredRelationship            6
VehicleMake                   14
VehicleModel                  39
dtype: int64

## 2.2 Categorical processing with One-Hot-Encoder

In [27]:
df_c = df.select_dtypes(include = 'O')

In [28]:
df_n = df.select_dtypes(exclude = 'O')

In [29]:
df_n

,ReportedFraud,SeverityOfIncident,IncidentTime,NumberOfVehicles,BodilyInjuries,Witnesses,AmountOfInjuryClaim,AmountOfPropertyClaim,AmountOfVehicleDamage,InsuredAge,InsuredZipCode,InsuredGender,InsuredEducationLevel,CapitalGains,CapitalLoss,InsurancePolicyNumber,CustomerLoyaltyPeriod,Policy_Deductible,PolicyAnnualPremium,VehicleYOM
0,0,3,19,3,1,1,9396.0,4698.0,29879.0,58,471784,1,4,0,-42700,129186,432,2000,1142.87,2005
1,0,1,14,1,1,1,6539.0,6539.0,49232.0,34,431937,0,0,51300,0,146710,128,1000,1274.38,2010
2,0,2,21,3,0,0,6069.0,6069.0,30686.0,52,479320,0,6,0,0,133433,346,745,1269.93,2002
3,1,2,12,3,2,0,253.0,5741.0,39678.0,25,607763,0,2,47400,-56100,114614,42,986,1218.60,2011
4,1,2,3,3,1,2,7407.0,14813.0,59252.0,27,441783,1,3,0,0,116825,109,576,1431.02,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27144,0,1,16,1,1,2,5543.0,5543.0,39429.0,39,454139,1,4,0,0,118894,251,1000,1108.55,2002
27145,0,3,19,3,2,0,8678.0,8738.0,76245.5,21,463809,1,1,20000,-75000,147560,14,1008,1551.84,2014
27146,0,3,16,3,2,0,13224.0,7990.0,66679.0,35,444155,1,1,0,-75000,147565,153,660,1119.32,2013
27147,0,0,12,1,1,1,728.0,1457.0,5099.0,40,603123,0,3,0,-63900,135587,241,1674,1229.88,2004
27148,0,3,11,1,2,3,15757.0,16322.0,58255.0,27,463291,0,6,51100,0,138676,113,500,1341.72,2009

In [30]:
dummies_df_c = pd.get_dummies(df_c, drop_first = True)

In [31]:
dummies_df_c

,TypeOfIncident_Parked Car,TypeOfIncident_Single Vehicle Collision,TypeOfIncident_Vehicle Theft,AuthoritiesContacted_Fire,AuthoritiesContacted_None,AuthoritiesContacted_Other,AuthoritiesContacted_Police,IncidentState_State4,IncidentState_State5,IncidentState_State6,...,VehicleModel_Pathfinder,VehicleModel_RAM,VehicleModel_RSX,VehicleModel_Silverado,VehicleModel_TL,VehicleModel_Tahoe,VehicleModel_Ultima,VehicleModel_Wrangler,VehicleModel_X5,VehicleModel_X6
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27144,0,1,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
27145,0,0,0,0,0,0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,0
27146,0,0,0,0,0,0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,0
27147,1,0,0,0,1,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
27148,0,1,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [32]:
df1 = pd.concat([df_n, dummies_df_c], axis = 1)

In [33]:
df1

,ReportedFraud,SeverityOfIncident,IncidentTime,NumberOfVehicles,BodilyInjuries,Witnesses,AmountOfInjuryClaim,AmountOfPropertyClaim,AmountOfVehicleDamage,InsuredAge,...,VehicleModel_Pathfinder,VehicleModel_RAM,VehicleModel_RSX,VehicleModel_Silverado,VehicleModel_TL,VehicleModel_Tahoe,VehicleModel_Ultima,VehicleModel_Wrangler,VehicleModel_X5,VehicleModel_X6
0,0,3,19,3,1,1,9396.0,4698.0,29879.0,58,...,0,0,0,0,0,0,0,0,0,0
1,0,1,14,1,1,1,6539.0,6539.0,49232.0,34,...,0,0,0,0,0,0,0,0,0,0
2,0,2,21,3,0,0,6069.0,6069.0,30686.0,52,...,0,0,0,0,0,0,0,0,0,0
3,1,2,12,3,2,0,253.0,5741.0,39678.0,25,...,0,0,0,0,0,0,0,0,0,0
4,1,2,3,3,1,2,7407.0,14813.0,59252.0,27,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27144,0,1,16,1,1,2,5543.0,5543.0,39429.0,39,...,0,0,1,0,0,0,0,0,0,0
27145,0,3,19,3,2,0,8678.0,8738.0,76245.5,21,...,0,0,1,0,0,0,0,0,0,0
27146,0,3,16,3,2,0,13224.0,7990.0,66679.0,35,...,0,0,1,0,0,0,0,0,0,0
27147,0,0,12,1,1,1,728.0,1457.0,5099.0,40,...,0,0,1,0,0,0,0,0,0,0
27148,0,3,11,1,2,3,15757.0,16322.0,58255.0,27,...,0,0,1,0,0,0,0,0,0,0

## 2.3. Train-test splitting and Standardization

In [34]:
X = df1.drop(columns = ['ReportedFraud'])
y = df1['ReportedFraud']

In [35]:
X.shape, y.shape

((27149, 136), (27149,))

In [36]:
col_names = X.columns
col_names

Index(['SeverityOfIncident', 'IncidentTime', 'NumberOfVehicles',
       'BodilyInjuries', 'Witnesses', 'AmountOfInjuryClaim',
       'AmountOfPropertyClaim', 'AmountOfVehicleDamage', 'InsuredAge',
       'InsuredZipCode',
       ...
       'VehicleModel_Pathfinder', 'VehicleModel_RAM', 'VehicleModel_RSX',
       'VehicleModel_Silverado', 'VehicleModel_TL', 'VehicleModel_Tahoe',
       'VehicleModel_Ultima', 'VehicleModel_Wrangler', 'VehicleModel_X5',
       'VehicleModel_X6'],
      dtype='object', length=136)

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [38]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((21719, 136), (21719,), (5430, 136), (5430,))

In [39]:
df_X_train = pd.DataFrame(X_train, columns = col_names)
df_X_test = pd.DataFrame(X_test, columns = col_names)

In [40]:
df_X_train

,SeverityOfIncident,IncidentTime,NumberOfVehicles,BodilyInjuries,Witnesses,AmountOfInjuryClaim,AmountOfPropertyClaim,AmountOfVehicleDamage,InsuredAge,InsuredZipCode,...,VehicleModel_Pathfinder,VehicleModel_RAM,VehicleModel_RSX,VehicleModel_Silverado,VehicleModel_TL,VehicleModel_Tahoe,VehicleModel_Ultima,VehicleModel_Wrangler,VehicleModel_X5,VehicleModel_X6
21334,1,22,1,2,2,13977.0,13977.0,42877.0,58,472236,...,0,0,0,0,0,0,0,0,0,0
24031,0,5,1,2,0,1183.0,661.0,5147.0,27,601112,...,0,0,0,0,0,0,0,0,0,0
8510,2,15,1,2,3,6215.0,9107.0,34765.0,38,434206,...,0,0,0,1,0,0,0,0,0,0
17052,3,18,3,1,2,14961.0,14961.0,56987.0,44,439929,...,0,0,0,0,0,0,0,0,1,0
6925,3,16,3,2,3,7393.0,467.0,48484.0,39,600313,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21575,1,9,1,1,3,12043.0,6021.0,42150.0,48,466498,...,0,0,0,0,0,0,0,0,0,0
5390,3,19,2,2,1,8078.0,8078.0,68825.0,26,463809,...,0,0,1,0,0,0,0,0,0,0
860,3,7,1,1,1,4826.0,8620.0,34481.0,41,607133,...,0,0,0,0,0,0,0,0,0,0
15795,3,1,1,1,0,8468.0,5401.0,40137.0,37,443522,...,0,0,0,0,0,0,0,0,0,0
23654,0,6,1,2,3,569.0,835.0,5049.5,44,469220,...,0,0,0,0,0,0,0,1,0,0

In [41]:
scale = StandardScaler()
X_train_scaled = scale.fit_transform(X_train)
X_test_scaled = scale.transform(X_test)

In [42]:
X_train_scaled.shape, X_test_scaled.shape

((21719, 136), (5430, 136))

In [43]:
df_X_train_scaled = pd.DataFrame(X_train_scaled, columns = col_names)
df_X_test_scaled = pd.DataFrame(X_test_scaled, columns = col_names)

In [44]:
df_X_train_scaled

,SeverityOfIncident,IncidentTime,NumberOfVehicles,BodilyInjuries,Witnesses,AmountOfInjuryClaim,AmountOfPropertyClaim,AmountOfVehicleDamage,InsuredAge,InsuredZipCode,...,VehicleModel_Pathfinder,VehicleModel_RAM,VehicleModel_RSX,VehicleModel_Silverado,VehicleModel_TL,VehicleModel_Tahoe,VehicleModel_Ultima,VehicleModel_Wrangler,VehicleModel_X5,VehicleModel_X6
0,-0.757628,1.679184,-0.812326,1.286021,0.484845,1.505300,1.542087,0.289712,2.447573,-0.418054,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
1,-1.785419,-1.098216,-0.812326,1.286021,-1.439209,-1.371709,-1.500071,-1.828482,-1.481041,1.364772,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
2,0.270162,0.535549,-0.812326,1.286021,1.446872,-0.240155,0.429492,-0.165702,-0.087017,-0.944147,...,-0.179097,-0.21796,-0.121898,6.609788,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
3,1.297953,1.025678,1.347281,0.007944,0.484845,1.726574,1.766891,1.081860,0.673360,-0.864977,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,6.274543,-0.126485
4,1.297953,0.698925,1.347281,1.286021,1.446872,0.024744,-1.544392,0.604494,0.039713,1.353719,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21714,-0.757628,-0.444710,-0.812326,0.007944,1.446872,1.070398,-0.275532,0.248898,1.180278,-0.497431,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
21715,1.297953,1.189055,0.267477,1.286021,-0.477182,0.178782,0.194408,1.746455,-1.607771,-0.534630,...,-0.179097,-0.21796,8.203581,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
21716,1.297953,-0.771463,-0.812326,0.007944,-0.477182,-0.552501,0.318233,-0.181646,0.293172,1.448064,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
21717,1.297953,-1.751722,-0.812326,0.007944,-1.439209,0.266482,-0.417176,0.135887,-0.213746,-0.815273,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
21718,-1.785419,-0.934839,-0.812326,1.286021,1.446872,-1.509781,-1.460319,-1.833956,0.673360,-0.459776,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,4.615059,-0.159374,-0.126485

In [45]:
df_X_test_scaled

,SeverityOfIncident,IncidentTime,NumberOfVehicles,BodilyInjuries,Witnesses,AmountOfInjuryClaim,AmountOfPropertyClaim,AmountOfVehicleDamage,InsuredAge,InsuredZipCode,...,VehicleModel_Pathfinder,VehicleModel_RAM,VehicleModel_RSX,VehicleModel_Silverado,VehicleModel_TL,VehicleModel_Tahoe,VehicleModel_Ultima,VehicleModel_Wrangler,VehicleModel_X5,VehicleModel_X6
0,0.270162,-0.934839,-0.812326,-1.270132,0.484845,0.592321,0.614544,0.387903,0.419901,1.620113,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,6.256679,-0.160886,-0.216682,-0.159374,-0.126485
1,-0.757628,1.842561,1.347281,-1.270132,-1.439209,-0.195180,1.195286,0.596859,0.926819,1.566743,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
2,1.297953,1.352431,1.347281,-1.270132,1.446872,0.502147,-0.564075,-0.187316,0.673360,1.435835,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,4.615059,-0.159374,-0.126485
3,1.297953,-0.444710,-0.812326,0.007944,-1.439209,-0.409033,0.535497,0.224365,-1.734500,-0.971621,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
4,0.270162,1.189055,-0.812326,-1.270132,0.484845,-0.260393,0.682396,0.863079,1.813926,-0.359676,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5425,-0.757628,0.208796,-0.812326,0.007944,-0.477182,1.795160,-0.419461,1.184766,-1.481041,-0.934229,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
5426,0.270162,0.045420,-0.812326,-1.270132,-0.477182,1.407256,1.442479,1.214128,-0.847394,1.452477,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
5427,-1.785419,-0.934839,-0.812326,1.286021,-1.439209,-1.507757,-1.404347,-1.833956,-1.227582,-0.398562,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
5428,0.270162,-1.751722,-0.812326,0.007944,-0.477182,-0.557449,0.519048,0.033991,-1.227582,1.596430,...,-0.179097,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485
5429,1.297953,-1.915098,-0.812326,-1.270132,-0.477182,2.449312,-0.076316,1.048681,0.546631,-0.463041,...,5.583574,-0.21796,-0.121898,-0.151291,-0.157696,-0.159829,-0.160886,-0.216682,-0.159374,-0.126485

## 3. Models

In [46]:
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from xgboost import XGBClassifier
from sktools import GradientBoostingFeatureGenerator

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

## 3.1 KNeighborsClassifier

In [47]:
knn = KNeighborsClassifier()
scores_knn = cross_val_score(knn, X_train_scaled, y_train, cv=5)
scores_knn

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

array([0.92794659, 0.92518416, 0.92541436, 0.9288674 , 0.92746949])

## 3.2 Logistic regression

In [48]:
y_train.value_counts()

0    16018
1     5701
Name: ReportedFraud, dtype: int64

In [49]:
lreg = LogisticRegression()
scores_lreg = cross_val_score(lreg, X_train_scaled, y_train, cv=5)
scores_lreg

array([0.85336096, 0.84599448, 0.8485267 , 0.84162063, 0.85678103])

## 3.3 SVM

In [50]:
svc = SVC()
scores_svc = cross_val_score(svc, X_train_scaled, y_train, cv=5)
scores_svc

array([0.93416206, 0.93047882, 0.92955801, 0.93116943, 0.93276537])

In [51]:
np.mean(scores_svc)

0.9316267387370883

In [52]:
svc_poly = SVC(kernel='poly')
scores_svc_poly = cross_val_score(svc_poly, X_train_scaled, y_train, cv=5)
scores_svc_poly

array([0.93462247, 0.92932781, 0.928407  , 0.93001842, 0.9320746 ])

In [53]:
np.mean(scores_svc_poly)

0.9308900586833705

In [54]:
svc_sig = SVC(kernel='sigmoid')
scores_svc_sig = cross_val_score(svc_sig, X_train_scaled, y_train, cv=5)
scores_svc_sig

array([0.77302026, 0.76588398, 0.76680479, 0.76289134, 0.76398803])

## 3.4 Decision Tree

In [55]:
dt = DecisionTreeClassifier()
scores_dt = cross_val_score(dt, X_train_scaled, y_train, cv=5)
scores_dt

array([0.86924494, 0.85888582, 0.8657919 , 0.87016575, 0.86714253])

## 3.5 Random Forrest

In [56]:
rf = RandomForestClassifier(random_state = 42)
scores_rf = cross_val_score(rf, X_train, y_train, cv=5)
scores_rf

array([0.93186004, 0.928407  , 0.92955801, 0.93139963, 0.93598895])

In [57]:
np.mean(scores_rf)

0.9314427250896747

## 3.6 AdaBoost with random forests

In [58]:
rf = RandomForestClassifier(random_state = 42)
ada = AdaBoostClassifier(rf)
scores_ada = cross_val_score(ada, X_train, y_train, cv=5)
scores_ada

array([0.93278085, 0.93001842, 0.92955801, 0.93047882, 0.93690997])

In [59]:
np.mean(scores_ada)

0.9319492131662095

## 3.7 GradientBoostingClassifier

In [60]:
GB = GradientBoostingClassifier(random_state = 42)
scores_GB = cross_val_score(GB, X_train, y_train, cv=5)
scores_GB

array([0.93093923, 0.93093923, 0.93047882, 0.92610497, 0.93253511])

In [61]:
np.mean(scores_GB)

0.9301994721507356

## 3.8 XGBoost

In [62]:
xgb = XGBClassifier(random_state = 42)
scores_XGB = cross_val_score(xgb, X_train, y_train, cv=5)
scores_XGB

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:08:44] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:08:52] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:01] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:10] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:18] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

array([0.93577348, 0.93669429, 0.93416206, 0.93577348, 0.93714023])

In [63]:
np.mean(scores_XGB)

0.9359087081135199

In [64]:
xgb

XGBClassifier(base_score=None, booster=None, colsample_bylevel=None,
              colsample_bynode=None, colsample_bytree=None,
              enable_categorical=False, gamma=None, gpu_id=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_delta_step=None, max_depth=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=42, reg_alpha=None, reg_lambda=None,
              scale_pos_weight=None, subsample=None, tree_method=None,
              validate_parameters=None, verbosity=None)

## 3.9 Grid Search for the best model

In [65]:
xgb = XGBClassifier(random_state = 42)
params_xgb = {'n_estimators': [10, 20, 40, 80, 100, 160, 320]}
grid_xgb = GridSearchCV(xgb, param_grid = params_xgb, cv = 5)
grid_xgb.fit(X_train, y_train)

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:27] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:28] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:29] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:30] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:31] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:32] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:34] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:36] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:38] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:40] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:42] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:45] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:49] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:53] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:09:56] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:10:00] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:10:07] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:10:14] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:10:21] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:10:28] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:10:34] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:10:43] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:10:52] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:11:01] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:11:09] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:11:18] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:11:33] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:11:47] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:12:01] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:12:15] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:12:29] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:12:56] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:13:23] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:13:51] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:14:18] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/hctran/opt/anaconda3/lib/python3.9/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[12:14:45] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None,
                                     enable_categorical=False, gamma=None,
                                     gpu_id=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_delta_step=None,
                                     max_depth=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     n_estimators=100, n_jobs=None,
                                     num_parallel_tree=None, predictor=None,
                                     random_state=42, reg_alpha=None,
                                     reg_lambda=None, scale_pos_weight=None,
                                     subsample=None, tree_method=None,
                                     validate_parameters=None, verbosity=None),
             param_grid={'n_estimators': [10, 20, 40, 80, 100, 160, 320]})

In [66]:
grid_xgb.best_estimator_,grid_xgb.best_score_

(XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
               colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
               gamma=0, gpu_id=-1, importance_type=None,
               interaction_constraints='', learning_rate=0.300000012,
               max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
               monotone_constraints='()', n_estimators=40, n_jobs=4,
               num_parallel_tree=1, predictor='auto', random_state=42,
               reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
               tree_method='exact', validate_parameters=1, verbosity=None),
 0.9374280769333518)

In [67]:
best_model = grid_xgb.best_estimator_

In [68]:
best_model

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=40, n_jobs=4,
              num_parallel_tree=1, predictor='auto', random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

## 4. Conclusion

It seems that XGBoost with 40 estimators is the best model above. Now we check the final model performace on the test set.

In [69]:
best_model.fit(X_train, y_train)

[12:14:50] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=40, n_jobs=4,
              num_parallel_tree=1, predictor='auto', random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [70]:
y_train_pred = best_model.predict(X_train)
y_test_pred = best_model.predict(X_test)

In [71]:
print('The classification report for the performance on the test set:\n', classification_report(y_test,y_test_pred))

The classification report for the performance on the test set:
               precision    recall  f1-score   support

           0       0.93      0.98      0.96      3953
           1       0.94      0.81      0.87      1477

    accuracy                           0.94      5430
   macro avg       0.94      0.90      0.92      5430
weighted avg       0.94      0.94      0.93      5430

In [72]:
print('The classification report for the performance on the train set:\n', classification_report(y_train,y_train_pred))

The classification report for the performance on the train set:
               precision    recall  f1-score   support

           0       0.95      0.98      0.96     16018
           1       0.95      0.84      0.89      5701

    accuracy                           0.95     21719
   macro avg       0.95      0.91      0.93     21719
weighted avg       0.95      0.95      0.94     21719